# Тема 10. Декораторы и исключения
Отчет по Теме №10 выполнил:
- Давтян Артём Артурович
- ИВТ-22-1

| Задание | Лаб_раб | Сам_раб |
| ------ |---------|---------|
| Задание 1 | +       | +       |
| Задание 2 | +       | +       |
| Задание 3 | +       | +       |
| Задание 4 | +       | +       |
| Задание 5 | +       | +       |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №1
### Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из этого декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи. P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.

```python
from functools import lru_cache

@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)

print(fibonacci(100))
```
### Результат.

![image](https://github.com/user-attachments/assets/2c651e75-9827-4707-a9f6-83d192cc2b3f)

### Выводы
Данный код демонстрирует реализацию вычисления чисел Фибоначчи с использованием мемоизации через декоратор lru_cache из модуля functools. 

## Лабораторная работа №2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130. Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.

```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)

    return output_func

@check
def personal_info(name, age):
    print(f"Name: {name} Age: {age}")

personal_info('Альберт', 74)
personal_info('Артур', -12)
personal_info('Артём', 150, 0, 20)
```

### Результат.

![image](https://github.com/user-attachments/assets/db03c435-f770-49ce-8bb1-4bf052032e98)

### Выводы
Данный код демонстрирует использование декоратора для проверки входных параметров функции.

## Лабораторная работа №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.

```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')

data([1, 15, 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```
### Результат.

![image](https://github.com/user-attachments/assets/f0caeb68-2607-40c4-ab43-d18e2b65e5e7)

### Выводы
Данный код демонстрирует обработку данных с использованием вложенных блоков try-except.

## Лабораторная работа №4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация”

```python
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name) > 10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешная регистрация')

name = '123456788910'
check_name(name)
```
### Результат.

![image](https://github.com/user-attachments/assets/f941ddac-e33d-4bb6-9891-0e7d122c2413)

### Выводы
Данный код демонстрирует создание пользовательского исключения NegativeValueException и его использование для проверки длины строки имени. 

## Лабораторная работа №5
### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: init() (вызывается при создании класса декоратора в программе) и call() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

```python
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('> Проверка перед запуском', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')


@SiteChecker
def site():
    print('Усердная работа сайта')

print('>> Сайт запущен')
site()
print('>> Сайт выключен')
```
### Результат.

![image](https://github.com/user-attachments/assets/912204b5-ff1c-4633-9875-7a7d6cf77722)

### Выводы
Данный код демонстрирует использование класса в качестве декоратора для проверки перед запуском и завершением работы функции, представляющей сайт. 

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
### Подсказка: необходимо использовать модуль time

```python
import time

def measure_time(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Время выполнения функции: {end_time - start_time:.6f} секунд")
        return result
    return wrapper

@measure_time
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')
    print()

fibonacci()
```
### Результат.

![image](https://github.com/user-attachments/assets/4d9f088b-8294-42c2-ba77-e6147fa5f49f)

### Выводы
Данный код демонстрирует использование декоратора для измерения времени выполнения функции. Декоратор measure_time оборачивает целевую функцию, фиксируя время начала и окончания её выполнения, а также выводя время, затраченное на выполнение функции, в секундах. 
  
## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file(filename):
    try:
        with open(filename, 'r', encoding='utf-8') as file:
            content = file.read()
            if not content:
                raise ValueError("файл пустой")
            print("Содержимое файла:")
            print(content)
    except ValueError as e:
        print(e)
    except FileNotFoundError:
        print("Файл не найден")

read_file("test.txt")
```
### Результат.

![image](https://github.com/user-attachments/assets/83eac93e-b531-4d73-adbe-fcfd02234915)

### Выводы
Данный код демонстрирует обработку ошибок при работе с файлами. Функция read_file пытается открыть и прочитать содержимое указанного файла. В случае, если файл не найден, выводится сообщение об ошибке FileNotFoundError.

## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.

```python
def add_two_to_input():
    try:
        user_input = input("Введите число: ")
        number = float(user_input)
        result = 2 + number
        print(f"Результат сложения: {result}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

add_two_to_input()

add_two_to_input()
```
### Результат.

![image](https://github.com/user-attachments/assets/f75f5dd4-da3e-4bf1-9cf6-b092fefd21e1)

### Выводы
Данный код демонстрирует обработку пользовательского ввода и управление исключениями при преобразовании строки в число. Функция add_two_to_input запрашивает у пользователя ввод числа, пытаясь конвертировать его в тип float. Если ввод содержит неподходящий тип данных, вызывает исключение ValueError, которое обрабатывается и выводит сообщение об ошибке. 

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class RepeatDecorator:
    def __init__(self, times):
        self.times = times

    def __call__(self, func):
        def wrapper(*args, **kwargs):
            for i in range(self.times):
                print(f"Выполнение {i + 1} из {self.times}")
                func(*args, **kwargs)
        return wrapper

@RepeatDecorator(times=3)
def print_hello():
    print("Привет!")

counter = 0

@RepeatDecorator(times=5)
def increment_counter():
    global counter
    counter += 1
    print(f"Текущее значение счетчика: {counter}")

print("Запуск функции print_hello:")
print_hello()

print("\nЗапуск функции increment_counter:")
increment_counter()
```
### Результат.

![image](https://github.com/user-attachments/assets/7b2ad3a2-d5eb-49f6-a856-4673363e665e)

### Выводы
Данный код демонстрирует использование класса-декоратора для повторного выполнения функций определенное число раз. Класс RepeatDecorator принимает параметр times, который указывает, сколько раз следует выполнить декорируемую функцию. Метод call оборачивает целевую функцию в дополнительную логику, выполняя её указанное количество раз и выводя номер текущего выполнения. В коде представлены две функции: print_hello, которая выводит приветственное сообщение, и increment_counter, увеличивающая глобальный счетчик и выводящая его текущее значение. Тем не менее, класс-декоратор не будет работать корректно, поскольку в его определении отсутствует реализация метода __init__, а также некорректное использование декоратора.

## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class NegativeNumberError(Exception):
    def __init__(self, message="Отрицательное число недопустимо"):
        super().__init__(message)

import math

def calculate_square_root(value):
    if value < 0:
        raise NegativeNumberError("Ошибка: Нельзя вычислить квадратный корень из отрицательного числа.")
    return math.sqrt(value)

def subtract(a, b):
    result = a - b
    if result < 0:
        raise NegativeNumberError("Ошибка: Результат вычитания не может быть отрицательным.")
    return result

try:
    print("Вычисление квадратного корня из 9:")
    print(calculate_square_root(9))

    print("\nВычисление квадратного корня из -4:")
    print(calculate_square_root(-4))

except NegativeNumberError as e:
    print(e)

print("\n---\n")

try:
    print("Вычитание 5 - 3:")
    print(subtract(5, 3))

    print("\nВычитание 3 - 5:")
    print(subtract(3, 5))

except NegativeNumberError as e:
    print(e)
```
### Результат.

![image](https://github.com/user-attachments/assets/40aa2dd3-c727-4138-b46f-3a2998400a6e)

### Выводы
Данный код демонстрирует создание пользовательского исключения и его использование для обработки ошибок, связанных с отрицательными числами. Определен класс исключения NegativeNumberError, который используется для сигнализации о недопустимости операций, когда результаты могут быть отрицательными, например, при вычислении квадратного корня отрицательного числа или в результате вычитания. Функции calculate_square_root и subtract проверяют входные значения и вызывают пользовательское исключение при необходимости.

## Общие выводы по теме
В представленных примерах кода продемонстрированы ключевые концепции работы с декораторами и исключениями в Python. Декораторы позволяют модифицировать поведение функций без изменения их исходного кода, обеспечивая удобный способ оборачивать функции в дополнительную логику, такую как измерение времени выполнения или многократный вызов. Исключения, в свою очередь, предлагают механизм для обработки ошибок, что делает код более надежным и устойчивым к неожиданным ситуациям. 
